# Generated by Django 3.2.7 on 2021-09-25 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gameName', models.CharField(default='', max_length=250)),
                ('originalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discountPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gameName', models.CharField(default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('token', models.CharField(default='', max_length=250)),
                ('action', models.CharField(default='buy', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserStates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=250)),
                ('money', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('products', models.ManyToManyField(to='gameBackend.GameProducts')),
            ],
        ),
    ]
