# Generated by Django 3.2.7 on 2021-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstates',
            name='products',
        ),
        migrations.AddField(
            model_name='userstates',
            name='products',
            field=models.CharField(default='', max_length=25000),
        ),
    ]
